"""Replaceable numerical boundaries for C. No UI dependency in these ports."""
from typing import Protocol, TypedDict, Any

class MotorCommand(TypedDict):
    yawRate: float       # desired UI heading rate, rad/s
    forwardSpeed: float  # drive reference mm/s; not guaranteed measured velocity
    verticalSpeed: float # zero in B

class NeuralBackend(Protocol):
    def step(self,sensors:dict,dt:float,config:dict)->MotorCommand: ...
    def snapshot(self)->dict: ...
    def restore(self,state:dict)->None: ...

class BodyBackend(Protocol):
    backend: str
    def pose(self)->tuple: ...
    def step(self,command:MotorCommand,dt:float)->None: ...
    def frame(self)->tuple[dict,dict]: ...
    def snapshot(self)->dict: ...
    def restore(self,state:dict)->None: ...
    def close(self)->None: ...
