"""Structural interfaces for independent numerical, readout and storage backends."""
from typing import Protocol
import numpy as np


class NeuralBackend(Protocol):
    tick: int
    backend: str
    def advance(self, drive: np.ndarray, steps: int, capture=(), pulses=None) -> None: ...
    def readout(self, indices) -> dict[str, np.ndarray]: ...
    def region_summary(self, groups) -> list[dict]: ...
    def snapshot(self) -> dict: ...
    def restore(self, state: dict) -> None: ...


class NeuralReadout(Protocol):
    def readout(self, indices) -> dict[str, np.ndarray]: ...
    def summary(self) -> dict: ...


class MotorDecoder(Protocol):
    def decode(self, backend: NeuralReadout) -> tuple[dict, dict]: ...


class Recorder(Protocol):
    def signal(self, tick: int, voltage, rate) -> None: ...
    def body(self, record: dict) -> None: ...
    def event(self, record: dict) -> None: ...
    def close(self, status='COMPLETE', reason=None) -> None: ...
