"""Synchronous neural boundary; snapshots remain model-specific dictionaries.

Engine pulses are positional for existing callers. Research reward is keyword
only, so it cannot be mistaken for a pulse matrix. Async Metal execution is an
optional optimization and does not change this contract.
"""
from typing import Protocol, runtime_checkable


@runtime_checkable
class NeuralBackend(Protocol):
    backend: str
    tick: int
    last_events: list

    def advance(self, drive, steps, capture=(), pulses=None): ...
    def set_interventions(self, suppress=(), mute=(), edges=()): ...
    def readout(self, indices): ...
    def summary(self): ...
    def region_summary(self, groups): ...
    def snapshot(self): ...
    def restore(self, state): ...
